(function(){
  var E={name:el('cc-name'),email:el('cc-email'),image:el('cc-image'),count:el('cc-count'),countLabel:el('cc-count-label'),zoom:el('cc-zoom'),fileType:el('cc-filetype'),grid:el('cc-grid'),download:el('cc-download'),emailSend:el('cc-email-send'),status:el('cc-status')};
  function el(id){return document.getElementById(id);} var HEX_W=116,HEX_H=132;
  var state={img:'',count:6,zoom:1.2};
  function autoLayout(n){var p=[];var cols=Math.ceil(Math.sqrt(n));for(var i=0;i<n;i++){var r=Math.floor(i/cols),c=i%cols;p.push({row:r,col:c});}return p;}
  function positions(){return autoLayout(state.count).map(function(p){return {x:p.col*104 + (p.row%2?52:0),y:p.row*88,row:p.row,col:p.col};});}
  function bounds(pos){var minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;pos.forEach(function(p){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x+HEX_W);maxY=Math.max(maxY,p.y+HEX_H);});return {minX:minX,minY:minY,width:maxX-minX,height:maxY-minY};}
  function render(){E.countLabel.textContent=String(state.count);E.grid.innerHTML='';var pos=positions();if(!pos.length)return;var b=bounds(pos);var gridW=Math.round(Math.max(1,b.width));var gridH=Math.round(Math.max(1,b.height));var zoom=state.zoom;var canvasW=Math.round(gridW*zoom),canvasH=Math.round(gridH*zoom);var zoomOffX=Math.round((canvasW-gridW)/2),zoomOffY=Math.round((canvasH-gridH)/2);E.grid.style.cssText='position:relative;width:'+gridW+'px;height:'+gridH+'px;margin:20px auto';
    pos.forEach(function(p,idx){var tileLeft=Math.round(p.x-b.minX),tileTop=Math.round(p.y-b.minY);var hex=document.createElement('div');hex.className='hex';hex.style.left=tileLeft+'px';hex.style.top=tileTop+'px';if(state.img){var img=document.createElement('img');img.src=state.img;img.style.width=canvasW+'px';img.style.height=canvasH+'px';img.style.maxWidth='none';img.style.left=Math.round(-(tileLeft*zoom+zoomOffX))+'px';img.style.top=Math.round(-(tileTop*zoom+zoomOffY))+'px';hex.appendChild(img);}var lab=document.createElement('span');lab.textContent=idx+1;lab.style.cssText='position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font:600 14px "DM Mono",monospace;color:#fff;text-shadow:0 1px 4px #000';hex.appendChild(lab);E.grid.appendChild(hex);});}
  function payload(){return {version:2,geometry:'pointy_hex',type:'consumer_custom_set',draftOnly:true,name:E.name.value.trim(),customerEmail:E.email.value.trim(),image:state.img,pieces:state.count,mainZoom:state.zoom,positions:autoLayout(state.count),createdAt:new Date().toISOString()};}
  function download(){var data=payload();var ext=E.fileType.value==='snova'?'snova':'json';var blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(data.name||'custom-set')+'.'+ext;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},1500);setStatus('Downloaded '+a.download);}  
  function sendEmail(){var data=payload();if(!data.customerEmail){setStatus('Email required');return;}fetch('/.netlify/functions/submit-custom-set',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(function(r){if(!r.ok)throw new Error('Unable to submit');return r.json();}).then(function(res){setStatus('Sent as '+(res.file||'draft file')+'. It remains draft-only.');}).catch(function(e){setStatus(e.message);});}
  function setStatus(msg){E.status.textContent=msg;}
  E.count.addEventListener('input',function(){state.count=parseInt(this.value,10)||6;render();});E.zoom.addEventListener('input',function(){state.zoom=parseFloat(this.value)||1.2;render();});E.image.addEventListener('change',function(){var f=this.files&&this.files[0];if(!f)return;var rd=new FileReader();rd.onload=function(){state.img=rd.result;render();};rd.readAsDataURL(f);});E.download.addEventListener('click',download);E.emailSend.addEventListener('click',sendEmail);render();
})();
