[build]
  command = "echo 'No build step required'"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.well-known/apple-developer-merchantid-domain-association"
  [headers.values]
    Content-Type = "application/octet-stream"

[[redirects]]
  from = "/.well-known/apple-developer-merchantid-domain-association"
  to = "/.well-known/apple-developer-merchantid-domain-association"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/faqs"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/faqs.html"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/shipping"
  to = "/shipping.html"
  status = 200
